services:
  - type: web
    name: face-verified-voting-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        sync: false
      - key: LOCAL_MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGINS
        sync: false

  - type: web
    name: face-verified-voting-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_BASE_URL
        sync: false
